### ISSUE TITLE
Installation of a custom Roboconf plugin

### ISSUE THREAD

**Issue by cdeneux** [roboconf/roboconf-platform#388] opened 2015-07-09 08:13 UTC
I have written a roboconf plugin to manage Petals ESB service unit. My roboconf application is  deployed on Docker containers. All my container images are generated from the base image `ubuntu:15:04`

The only way to install the Roboconf plugin is to create manually my own images embedding the Robonconf plugin. **As my images are generated by Roboconf, I can't install the Roboconf plugin**. So another way should be available.

Moreover, I think that the production operator has not to install the Robocong plugin in the Roboconf agent. It can be potentially installed into the Roboconf DM that will push the Roboconf plugin in the right Roboconf agent instances (which ones that need it, according to the application graph).

**Comment by bourretp** [comment] 2015-07-20 10:03
I think the problem could be fixed by specifying a list of artefacts to copy in the Karaf `deploy` directory, so they are started along with the agent. By artefact I mean bundles, or anything Karaf can deploy (configuration, maybe even coffee). So you can put your Roboconf plugin bundle + its dependencies + its configuration.

For the other point (reworded as "operator don't care about plugins"), there may be a way to detect which plugin we need to deploy on the agent, by reading the application model. But, the problem is: how could we translate that to a list of artefacts to deploy:
- get `roboconf-plugin-<<name>>` from Maven central. Only works for released Roboconf "official" plugins, as we cannot specify custom groudId/artifactId/version/repository.
- what about the plugin's dependencies?
- maybe the easiest approach is to rely on Karaf's features. Each plugin has an associated feature (let's say `roboconf-plugin-<<name>>-feature`), and Roboconf deploys this feature on the agent. But that is another story (and another issue IMO).

WDYT?

**Comment by vincent-zurczak** [comment] 2015-07-20 10:35
For the operator thing...
If additional plugins have to be installed on an agent, they should be specified in the **target.properties** file. We cannot automate anything because a plugin is not mandatory official. There may be no public access too.

It is also possible to dynamically add a new instance on the agent that requires another installer. So, even if we wanted to automate things, it would not be up to the DM to deal with it, but with the agent to download the plug-ins it needs, and when it needs them. If we wanted to do so, we should take a look at OSGi related projects at Apache. I am quite sure some of them can deal with that, but that will complexify the installation of Roboconf.

For the moment, let's keep it simple: we specify a list of URLs in the target.properties file. And we deploy these artifacts in the generated image.

**Comment by cdeneux** [comment] 2015-07-20 12:48
A list of Urls in the target.properties, or a list of files embedded into the Roboconf application archive.

In a Roboconf application developper point of view, these Urls or files should be added by the Roboconf maven plugin in its configuration part, something like:

    <plugin>
               <groupId>net.roboconf</groupId>
               <artifactId>roboconf-maven-plugin</artifactId>
               <version>${roboconf.version}</version>
               <extensions>true</extensions>
               <configuration>
                        <plugins>
                               <plugin>
                                        <groupId>...</groupId>
                                        <artifactId>...</artifactId>
                                        <version>...</version>
                               </plugin>
                        </plugins>
               </configuration>
    </plugin>

**Comment by bourretp** [comment] 2015-07-21 13:30
Ok, your proposal looks nice, but the deployment should allow other artefacts to be deployed, not only plugins. I suggest something more generic, like:

```xml
<configuration>
    <artifacts>
        <artifact>
            <groupId>...</groupId>
            <artifactId>...</artifactId>
            <version>...</version>
        </artifact>
    </artifacts>
</configuration>
```

That kind of thing can easily be translated to a `mvn:` URL. But it should also be possible to deploy an arbitrary resource, referred by its URL:

```xml
        <artifactUrl>
            https://www.private.org/secret_target.properties
        </artifactUrl>
```

I'm working on the target-docker side of this improvement, so be adding a `docker.additional.deploy` property (like for the packages): a space-separated list of URLs the agent will wget before it starts.

**Comment by vincent-zurczak** [comment] 2015-07-21 13:32
I don't think  it is a good idea to put anything more in the POM of Roboconf applications.
Like I said, this is only about Docker for the moment. Let's keep it in the **target.properties**. We will review the generation mechanism when it arises in other targets. :sweat_smile:

**Comment by bourretp** [comment] 2015-07-22 12:26
Fixed! Merge is pending in PR roboconf/roboconf-platform/pull/397

Should be available in the afternoon. Documentation is coming too...

**Closed** 2015-07-22 14:11 UTC
