### ISSUE TITLE
Add the support to create LXC containers in a IaaS VM

### ISSUE THREAD

**Issue by donsez** [roboconf/roboconf-platform#38] opened 2014-03-28 18:31 UTC
LXC (https://linuxcontainers.org/) enables to isolate processes in a Linux physical or virtual machines.

Add the support to create LXC containers in a IaaS VM in order to build PaaS (such as Heroku) for hosting services written in Ruby, Node.js, Clojure, Java, Python, Scala, Erlang ...

**Comment by vincent-zurczak** [comment] 2015-10-15 21:02
Somehow a duplicate of our Docker support.

**Closed by vincent-zurczak** 2015-10-15 21:02 UTC
Labels: duplicate, enhancement, wontfix
